Add screen warnings
ProcessMaker/screen-builder pull request #1024
Opened 2021-07-28 19:09 UTC by caleeli

Add screen warnings when the screen has a large number of controls or it is using watchers with scripts.

![image](https://user-images.githubusercontent.com/8028650/127381722-88ff85fd-98b9-41d0-a3f0-2fe5e282f583.png)

2021-07-28 20:50 UTC, danloa requested changes

2021-07-28 21:08 UTC, caleeli commented on src/form-control-common-properties.js
> +    helper: 'The default value is pre populated using the existing request data. This feature will allow you to modify the value displayed on screen load if needed.',
Missing translation added

2021-07-28 21:08 UTC, caleeli commented on src/components/watchers-form.vue
> +                {{ $t('Using watchers with Scripts can slow the performance of your screen.') }}
Missing translation added

2021-07-28 21:10 UTC, caleeli commented
@danloa thanks for the observation, the missing translations was added into the PR https://github.com/ProcessMaker/processmaker/pull/3911

2021-07-30 15:16 UTC, danloa approved these changes

2021-07-30 15:19 UTC, boliviacoca approved these changes

2021-07-30 15:20 UTC, merged