[4.2] calcs with nested screen, breaks the main screen
ProcessMaker/screen-builder pull request #1155
Opened 2022-01-12 20:39 UTC by marcoAntonioNina

## Issue & Reproduction Steps
- load screen from ticket.
- add parameters for the operation.
- the calculated field is not resolved.

Expected behavior: 
the calculated property must be set correctly.
Actual behavior: 
the calculated property is not displayed correctly.
## Solution
- validate that there is no loop when calculating the data in the mustache section.

## How to Test
- load screen from ticket.
- add parameters for the operation.
- the calculated field is resolved.

https://user-images.githubusercontent.com/1747025/149217964-73cdf69d-6959-4d1d-a4a9-b6c4b37b1a2a.mp4

## Related Tickets & Packages
- [FOUR-5084](https://processmaker.atlassian.net/browse/FOUR-5084)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2022-01-13 17:50 UTC, caleeli requested changes
Very nice change, could you add a test to verify the case?

2022-01-14 19:51 UTC, marcoAntonioNina commented
@caleeli  test added

2022-01-14 20:29 UTC, caleeli approved these changes
Very good

2022-01-14 20:44 UTC, ryancooley approved these changes

2022-01-14 20:45 UTC, merged