Bugfix FOUR-5131: File upload inside the loop is lost
ProcessMaker/screen-builder pull request #1195
Opened 2022-03-23 20:46 UTC by eiresendez

## Issue & Reproduction Steps

Expected behavior: 
- The files loaded from a file upload inside a loop in the record list, should not be lost when pressing the edit button of the record list.

Actual behavior: 
- Files loaded in the loop - record list have disappeared. 

## Solution
- Pulling the fixes of what was solved in 4.1.

## How to Test
You can run the following test: `RecordList.spec.js` and follow these steps:

1. Log in 
2. create a  screen
3. create  record  list
4. create  second page  for recorlist 
5. create a loop 
6. inside  loop create a file upload
7. start a new  request 
8. Click on Add  record list 
9. upload a file in the upload file that is inside the loop
10. add a new item
11. load a new file
12. click on save from the record list
13. click on the button edit

## Related Tickets & Packages
- [FOUR-5131](https://processmaker.atlassian.net/browse/FOUR-5131)
- [Pull Request for FOUR-4986 (4.1)](https://github.com/ProcessMaker/screen-builder/pull/1194)

2022-03-25 18:59 UTC, agustinbusso requested changes
All are working really fine except for File preview that is not working on the same screen. Is replicated also in webenty. Please watch the video:

https://user-images.githubusercontent.com/90727999/160184568-20f7fb17-d144-455c-b221-cdff6c7b7aaf.mov

2022-03-30 13:25 UTC, agustinbusso commented
In sync with the Team the file preview issue is out of the scope of this ticket. The original issue was correctly fixed and working as expected. Proceeding to approve the PR.
cc @boliviacoca

2022-03-30 13:26 UTC, agustinbusso approved these changes
In sync with the Team the file preview issue is out of the scope of this ticket. The original issue was correctly fixed and working as expected. Proceeding to approve the PR.
cc @boliviacoca

2022-04-01 20:30 UTC, ryancooley approved these changes

2022-04-01 20:30 UTC, merged