Refresh nested screen
ProcessMaker/screen-builder pull request #1203
Opened 2022-04-13 16:33 UTC by caleeli

## Issue & Reproduction Steps

- Create a nested screen with a couple of fields
- Create a form screen
- Add the nested screen
- On a new tab edit the nested screen
- Change the nested screen
- Go the tab of the parent screen

Actual behavior: 
There is no way to refresh the nested screen unless refreshing all the page

## Solution
- Reset the cache for the modified nested screen when change from Design <--> Preview

## How to Test
See the video:

https://user-images.githubusercontent.com/8028650/163227831-dea8a931-d573-4678-a094-2e5c8ddd4200.mp4

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-5933
- REQUIRES: https://github.com/ProcessMaker/processmaker/pull/4332

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2022-04-14 21:01 UTC, agustinbusso requested changes
Is working well in a first level deep but after add another nested screen level is not updating the screen. Please watch the following video

https://user-images.githubusercontent.com/90727999/163474388-e458be30-faf6-484b-8bcd-e24c4744513d.mov

2022-04-18 13:59 UTC, caleeli commented
@agustinbusso thanks for your report, the issue was fixed.

2022-04-18 14:59 UTC, agustinbusso approved these changes
Working as expected

https://user-images.githubusercontent.com/90727999/163827332-d26c4328-a827-40d9-82b1-1de1e4afe31f.mov

2022-04-22 05:00 UTC, ryancooley approved these changes

2022-04-22 05:00 UTC, merged