Bugfix/four 7009
ProcessMaker/screen-builder pull request #1277
Opened 2022-11-09 16:41 UTC by caleeli

## Issue & Reproduction Steps
Unable to access _parent parameter on calcs property in a Nested Screen inside a Loop.

Expected behavior: 
Access _parent parameter on calcs property in a Nested Screen inside a Loop.

Actual behavior: 
Unable to access _parent parameter on calcs property in a Nested Screen inside a Loop.

## Solution
- Fix _parent getter in Calc properties

## Related Tickets & Packages
- 

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2022-11-09 17:56 UTC, josechirivella commented on src/mixins/computedFields.js
>          e;
```suggestion
        console.error("There was a problem evaluating the expression", e);
```

2022-11-09 18:05 UTC, josechirivella requested changes
Github want's a comment

2022-11-09 20:49 UTC, caleeli commented on src/mixins/computedFields.js
>          e;
Added, but with warning level.

2022-11-09 22:24 UTC, rodriquelca approved these changes

2022-11-09 23:08 UTC, josechirivella approved these changes

2022-11-10 22:00 UTC, ryancooley approved these changes

2022-11-10 22:00 UTC, merged