Bugfix/FOUR-7111: Previewing a screen that contains a nested screen and another control causes two 404 error calls
ProcessMaker/screen-builder pull request #1290
Opened 2022-11-18 18:41 UTC by agustinbusso

## Issue & Reproduction Steps
**Steps to Reproduce:**

- Go to https://release-testing-qa.processmaker.net/ (PM 4.3.0-RC4)
- Go to Designer tab
- Go to screen option in sidebar menu
- Create a Form type screen
- Click on Add screen
- Fill a name and description
- In the type option, select “Form“
- Click on Save button
- Drag and drop a Nested Screen control.
- Drag a control of the following: Checkbox, Date Picker, File Upload, Google Places, Line Input, Loop, Record List, Select 
- List or Text Area (In the attached video I tested with a Text Area control)
- Open Devtools and go the network tab
- Click on Preview button

**Expected behavior:** 
A single call should be generated by the nested Screen.

**Actual behavior:** 
Two pop-ups with 404 error appear and two calls are generated.

## Solution
- Check if id exists before send the api request to retrieve the screen

**Working video**

https://user-images.githubusercontent.com/90727999/202778996-e4583dee-a14c-4c4a-a59d-6c15b49d3864.mov

## How to Test
Test the steps above

## Related Tickets & Packages
- [FOUR-7111](https://processmaker.atlassian.net/browse/FOUR-7111)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2022-11-18 20:01 UTC, josechirivella requested changes
Looks good but some minor changes that we need to check before executing the function.

2022-11-18 20:01 UTC, josechirivella commented on src/DataProvider.js
> +    }
I would place this after line 101

2022-11-18 20:01 UTC, josechirivella commented on src/ValidationsFactory.js
> +    if (!id) {
I would place this after line 91

2022-11-18 20:33 UTC, agustinbusso commented on src/ValidationsFactory.js
> +    if (!id) {
Thanks @josechirivella Done!

2022-11-18 21:25 UTC, josechirivella approved these changes

2022-11-22 12:26 UTC, ryancooley approved these changes

2022-11-22 12:26 UTC, merged