Signature not working in an image control inside a loop
ProcessMaker/screen-builder pull request #1291
Opened 2022-11-21 23:22 UTC by marcoAntonioNina

## Issue & Reproduction Steps
1. import the screen in the ticket
2. perform a signature with the signature component.
3. checking the loop and form image component, the image should be the same.
Expected behavior: 
variable _parent should be working with FormImage component
Actual behavior: 
variable _parent does not return the information
## Solution
- Add method get screen reference

## How to Test
use variable _parent for load data in FormImage Component

## Related Tickets & Packages
[FOUR-7108](https://processmaker.atlassian.net/browse/FOUR-7108)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2022-11-22 20:14 UTC, sanjacornelius approved these changes

2022-12-01 14:10 UTC, caleeli commented on src/components/renderer/form-image.vue
> +      if (this.mode === 'preview' ) {
This will only work in preview mode. It will always return undefined when you run a process inside a Request Task

2022-12-01 14:11 UTC, caleeli requested changes
Please fix the case when the screen is used outside the editor. (Runtime)

2022-12-01 15:58 UTC, caleeli approved these changes

2022-12-02 05:15 UTC, ryancooley approved these changes

2022-12-02 05:15 UTC, merged