FOUR-6854 Fixing E2E test to target the new datepicker
ProcessMaker/screen-builder pull request #1311
Opened 2023-01-05 20:17 UTC by josechirivella

## Issue & Reproduction Steps

Expected behavior: 
The E2E test for the date picker should pass targeting the new date picker

Actual behavior: 
They are not since they are targeting the old datepicker

## Solution
- Targeting the correct classes and functionality

## How to Test
Test the steps above

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-6854
- https://github.com/ProcessMaker/vue-form-elements/pull/376

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-01-10 14:20 UTC, caleeli commented on tests/e2e/specs/LoadComplexData.spec.js
> +      'FPP_USER_FULL_TIME': {
This should not be changed, because it was fixed by a previous PR (not yet merged): https://github.com/ProcessMaker/screen-builder/pull/1303

2023-01-10 14:20 UTC, caleeli commented on tests/e2e/specs/LoadComplexData.spec.js
> +      'FPP_USER_PART_TIME': {
This should not be changed, because it was fixed by a previous PR (not yet merged): https://github.com/ProcessMaker/screen-builder/pull/1303

2023-01-10 14:27 UTC, caleeli commented on tests/e2e/specs/ValidationRules.spec.js
> +  it.only('Invalid default values', () => {
Remove `.only`
```suggestion
  it('Invalid default values', () => {
```

2023-01-10 14:28 UTC, caleeli requested changes
Review the requested changes in comments

2023-01-11 14:16 UTC, rodriquelca approved these changes

2023-01-13 19:41 UTC, caleeli approved these changes

2023-02-17 19:58 UTC, merged