FOUR-7561 Test case for Default Values in the Datepicker
ProcessMaker/screen-builder pull request #1346
Opened 2023-03-09 20:12 UTC by josechirivella

## Issue & Reproduction Steps

Expected behavior:
We should have a test case to cover the scenario where the user sets a default value for the datepicker

Actual behavior: 
We do not have a test case for this case

## Solution
- Added the test scenario

## How to Test
Test the steps above
- Run Screen Builder with https://github.com/ProcessMaker/vue-form-elements/pull/383
- Run Cypress

## Related Tickets & Packages
- Ticket https://processmaker.atlassian.net/browse/FOUR-7564 actually solves the date formatting issue. This is only to add the test coverage
- https://processmaker.atlassian.net/browse/FOUR-7561

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-03-10 12:37 UTC, boliviacoca approved these changes

2023-03-10 14:01 UTC, rodriquelca approved these changes

2023-03-17 14:11 UTC, caleeli requested changes
Something changed or maybe was skipped previously by the test **ComputedFieldsReadOnly.spec.js** is failing, probably the test should be adjusted to the new control. Double check if you need to rebase the branch FOUR-7561

![image](https://user-images.githubusercontent.com/8028650/225928392-5c08cb36-d81b-4f97-90f7-5f974ceba22e.png)

![image](https://user-images.githubusercontent.com/8028650/225928615-73d67199-3cc7-4e9d-961d-4392d30d4f09.png)

2023-03-17 18:37 UTC, rodriquelca commented
checking the ComputedFieldsReadOnly.spec.js now is passing the test
<img width="1253" alt="Screen Shot 2023-03-17 at 14 36 43" src="https://user-images.githubusercontent.com/1401911/225990318-f1f72b54-7be6-4950-80f9-4f4f42291a64.png">

2023-03-17 19:24 UTC, rodriquelca approved these changes

2023-03-17 19:26 UTC, rodriquelca approved these changes

2023-03-17 21:47 UTC, merged