FOUR-13078: Clicking in view all request shows server error
ProcessMaker/screen-builder pull request #1529
Opened 2024-02-05 15:28 UTC by rodriquelca

## Issue & Reproduction Steps

Expected behavior: 
When an user clicks in view all request it should see all the requests.
Actual behavior: 
 Clicking in view all request shows server error
## Solution
- improve empty form url
- add server url as a global parameter

## How to Test
Test the steps above

1. Create a new user.
2. log in with the user, and make sure you are in the default home page dashboard
3. If there are no requests or tasks available Click to view all requests or tasks
4. See the error.
5. If your user has tasks and/or requests you won’t see the links but you can also try these URLs:

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-13078

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2024-02-05 16:23 UTC, fagubla requested changes

2024-02-05 16:23 UTC, fagubla commented on src/components/renderer/form-requests.vue
> +      return `${window.ProcessMaker?.app?.url}requests`;
add '/' before **requests**

2024-02-05 16:23 UTC, fagubla commented on src/components/renderer/form-tasks.vue
> +      return `${window.ProcessMaker?.app?.url}tasks`;
add '/' before **tasks**

2024-02-06 16:22 UTC, fagubla approved these changes

2024-02-06 16:25 UTC, boliviacoca approved these changes

2024-02-06 18:14 UTC, merged