Feature/FOUR-13370: The Avatar is not working correctly as Participant and Designer
ProcessMaker/screen-builder pull request #1531
Opened 2024-02-08 14:39 UTC by luNunezProcessmaker

## Issue & Reproduction Steps

The Avatar is not the same in Home Option and Designer Option, since is the same user that was login.

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-13370

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

2024-02-08 15:05 UTC, fagubla approved these changes

2024-02-08 15:05 UTC, fagubla commented on src/components/renderer/form-avatar.vue
> +      }
`return this.user.avatar ? "secondary" : "info";`

2024-02-08 15:05 UTC, fagubla commented on src/components/renderer/form-avatar.vue
> +        "px; padding:0;";
```javascript
return (
        `width: ${this.width}px; ` +
        `height: ${this.height}px; ` +
        `font-size:${this.height / 2.5}px; ` +
        "padding:0;"
      );
```

2024-02-08 18:13 UTC, fagubla requested changes

2024-02-08 18:13 UTC, fagubla commented on src/components/renderer/form-avatar.vue
> +      >
must be />

2024-02-08 18:33 UTC, fagubla approved these changes

2024-02-08 18:38 UTC, fagubla commented
@pmPaulis It'is working as the expected
[recording (1).webm](https://github.com/ProcessMaker/screen-builder/assets/5005237/4f652afc-2742-43e0-a5f5-bdb292b82705)

2024-02-09 17:42 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-424bf95af9.engk8s.processmaker.net

2024-02-09 20:14 UTC, merged