FOUR-15487:Phase1: Remove Analytics chart from future and existing customers in dev  (QuickSight related)
ProcessMaker/screen-builder pull request #1585
Opened 2024-05-10 20:14 UTC by fagubla

## Issue & Reproduction Steps
Remove Analytics chart from future and existing customers in dev (QuickSight related)
Expected behavior: 

Actual behavior: 

## Solution
-

## How to Test
Test the steps above

## Related Tickets & Packages
- [FOUR-15487](https://processmaker.atlassian.net/browse/FOUR-15487)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next
ci:package-dynamic-ui:feature/FOUR-15487

[FOUR-15487]: https://processmaker.atlassian.net/browse/FOUR-15487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-05-10 21:27 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-9a8ef20acc.engk8s.processmaker.net

2024-05-11 00:10 UTC, luNunezProcessmaker approved these changes

2024-05-13 12:59 UTC, ana-mauricio requested changes
The following observations were found :
1. The sizes of the cards are different (ANALYTICS CHART height is higher)
![image](https://github.com/ProcessMaker/screen-builder/assets/21198450/42857578-c1aa-45de-a194-3acff5ae14eb)
2. The Welcome user is above the avatar
![image](https://github.com/ProcessMaker/screen-builder/assets/21198450/c4cd9d7e-1566-4544-bfa0-85a56b88742f)
3. The image in Anakytics chart is not responsive  
https://github.com/ProcessMaker/screen-builder/assets/21198450/c6d3ad88-a185-46a9-b369-b184886dfd94


@fagubla

2024-05-13 13:30 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-9a8ef20acc.engk8s.processmaker.net

2024-05-13 16:26 UTC, ana-mauricio approved these changes
The WELCOME was corrected, and the others observations works as expected behavior 
@fagubla

2024-05-13 17:59 UTC, pmPaulis requested changes

2024-05-13 17:59 UTC, pmPaulis commented on src/components/renderer/form-analytics-chart.vue
> +      this.showChart = this.graphic.name === "PM Analytics Chart" || this.graphic.name === "PM Analytics Dashboard";
Please this default needs to show when the Analytics does not have any chart selected like: 
![image](https://github.com/ProcessMaker/screen-builder/assets/42388723/60579a40-346d-41ec-a197-db8aa4b42766)

2024-05-13 20:15 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-9a8ef20acc.engk8s.processmaker.net

2024-05-13 20:45 UTC, luNunezProcessmaker approved these changes

2024-05-13 20:47 UTC, luNunezProcessmaker approved these changes

2024-05-15 01:56 UTC, merged