Feature/four 16640
ProcessMaker/screen-builder pull request #1622
Opened 2024-06-17 15:50 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
Self Service stops filtering after a search on Welcome screen 

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-16640

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2024-06-17 16:24 UTC, fagubla requested changes

2024-06-17 16:24 UTC, fagubla commented on src/components/renderer/form-tasks.vue
> +          pmql =  pmql ? pmql + "AND" : "" + this.pmqlSearch;
remove the extra before **pmql**

2024-06-17 16:41 UTC, fagubla approved these changes

2024-06-17 17:25 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-0e1f940176.engk8s.processmaker.net

2024-06-18 13:46 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-0e1f940176.engk8s.processmaker.net

2024-06-18 20:31 UTC, fagubla requested changes

2024-06-18 20:31 UTC, fagubla commented on src/components/renderer/form-tasks.vue
> +        console.log("still here");
remove console

2024-06-19 00:12 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-0e1f940176.engk8s.processmaker.net

2024-06-19 13:47 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-0e1f940176.engk8s.processmaker.net

2024-07-13 16:16 UTC, closed without merging