FOUR-17516 It is not possible to filter all sections from the search …
ProcessMaker/screen-builder pull request #1664
Opened 2024-08-02 17:39 UTC by gproly

…within the screen

## Issue & Reproduction Steps

Expected behavior: The section written in search field should be displayed
Actual behavior: The section is not filtered

## How to Test
Search section fields

2024-08-02 19:11 UTC, CarliPinell approved these changes

2024-08-02 19:53 UTC, devmiguelangel requested changes

2024-08-02 19:53 UTC, devmiguelangel commented on src/components/vue-form-builder.vue
> +        let filter = this.filterQuery.toLowerCase();
Extract the filter query outside the `filter`  array method
```suggestion
      const filter = this.filterQuery.toLowerCase();
      const filtered = this.controls.filter((control) => {
```

2024-08-02 19:53 UTC, devmiguelangel commented on src/components/vue-form-builder.vue
> +        let result = control.label.toLowerCase(filter).includes();
The `toLowerCase` method doesn't accept parameters, maybe do you mean?
```suggestion
        let result = control.label.toLowerCase().includes(filter);
```

2024-08-05 18:11 UTC, devmiguelangel approved these changes

2024-08-09 19:46 UTC, merged