Allow scripts and data sources in sync mode
ProcessMaker/screen-builder pull request #972
Opened 2021-04-22 00:31 UTC by nolanpro

See https://github.com/ProcessMaker/processmaker/pull/3772

2021-04-22 18:37 UTC, caleeli approved these changes

2021-04-22 19:44 UTC, caleeli requested changes
The change looks very good. To complete the PR the Watchers tests also must be updated to the new implementation

2021-04-23 12:42 UTC, caleeli approved these changes

2021-04-23 12:45 UTC, boliviacoca approved these changes

2021-04-23 12:46 UTC, merged